{% set name = "skprogs" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}-python
  version: {{ version }}

source:
  url: https://github.com/dftbplus/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 220f7149557ef92b67c69450f9d7bb514de356b4db1571c5a9f20c9c4f0de79f

build:
  number: 0
  noarch: python
  entry_points:
    - collectspinw = sktools.scripts.collectspinw:main
    - collectwavecoeffs = sktools.scripts.collectwavecoeffs:main
    - skdiff = sktools.scripts.skdiff:main
    - skexp = sktools.scripts.skexp:main
    - skgen = sktools.scripts.skgen:main
    - skmanip = sktools.scripts.skmanip:main
  script: "{{ PYTHON }} -m pip install ./sktools -vv"

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy
    - scipy

test:
  imports:
    - sktools
  commands:
    - collectspinw -h
    - collectwavecoeffs -h
    - skdiff -h
    - skexp -h
    - skgen -h
    - skmanip -h

about:
  home: https://github.com/dftbplus/skprogs
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - "COPYING"
    - "COPYING.LESSER"
  summary: "Python tools to generate Slater-Koster files for the DFTB-method"
  doc_url: https://dftbplus-recipes.readthedocs.io
  dev_url: https://github.com/dftbplus/skprogs

extra:
  recipe-maintainers:
    - aradi
    - vanderhe
    - bhourahine
